set positional-arguments

# Build for the `cannon` target
build-cannon *args='':
  docker run \
    --rm \
    --platform linux/amd64 \
    -v `pwd`/../../:/workdir \
    -w="/workdir/examples/minimal" \
    cannon-pipeline:latest cargo build -Zbuild-std $@

# Build for the `asterisc` target
build-asterisc *args='':
  docker run \
    --rm \
    --platform linux/amd64 \
    -v `pwd`/../../:/workdir \
    -w="/workdir/examples/minimal" \
    asterisc-pipeline:latest cargo build -Zbuild-std $@
