# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 75..100
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%
    patch:
      default:
        target: auto
        # Avoid false negatives
        threshold: 1%
        base: auto 
        only_pulls: true

ignore:
  - "tests"
  - "test_util.rs"
  - "test_utils.rs"
  - "crates/derive/src/stages/test_utils"
  - "bin/"

# Make comments less noisy
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: false
