[workspace]
[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
kona-preimage = { path = "../../../crates/preimage", version = "0.0.2", features = [
    "serde",
] }
kona-common = { path = "../../../crates/common", version = "0.0.2" }
kona-client = { path = "../../client", version = "0.1.0" }
revm = { git = "https://github.com/bluealloy/revm", tag = "v37", version = "10.0.0", default-features = false }
anyhow = "1.0.86"

alloy-sol-types = "0.7.2"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.8-testnet" }

[features]
default = ["solo-client"]
solo-client = ["kona-preimage/solo-client", "kona-client/solo-client"]
