# Test all FPVM targets
test: test-cannon

# Test the program on `cannon`
test-cannon:
  # Build the programs
  @cd ../examples/simple-revm && just build-cannon --release
  # Run Cannon tests
  @cd cannon-tests && go test -count=1 -v ./...
