[package]
name = "zkvm-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
tracing.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }
revm = { workspace = true, features = ["std", "c-kzg", "secp256k1", "portable", "blst"] }
alloy-eips.workspace = true
alloy-consensus.workspace = true

# local
kona-common = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-preimage = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream", features = ["rkyv"] }
kona-primitives = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-mpt = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-derive = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream", default-features = false }
kona-executor = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-client = {  git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
zkvm-client = { path = "../../bin/programs/zkvm-client", version = "0.1.0" }

# external
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183" }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183" }
reqwest = "0.12"
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3"
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.198", features = ["derive"] }
tracing-subscriber = "0.3.18"
command-fds = { version = "0.3", features = ["tokio"] }
tempfile = "3.10"
alloy-rlp.workspace = true
serde_json = "1.0.117"
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
hashbrown = "0.14.5"
hex = "0.4.3"
bincode = "1.3.3"


[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }
