name: Build and Publish Cross Images
on: [workflow_dispatch, workflow_call]
env:
  REGISTRY: ghcr.io
jobs:
  build-pipelines:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: ["cannon", "asterisc"]
    env:
      IMAGE_NAME: ${{ github.repository }}/${{ matrix.target }}-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate with container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Publish `${{ matrix.target }}-pipeline`
        uses: docker/build-push-action@v5
        with:
          file: build/${{ matrix.target }}/${{ matrix.target }}.dockerfile
          context: build/${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
