on:
  schedule:
    # Runs "at 05:00, only on Monday" (see https://crontab.guru)
    - cron: "0 5 * * 1"

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: ethereum-optimism
          number: 60
          token: ${{ secrets.GITHUB_TOKEN }}
          iteration-field: Cycle
          iteration: last
          new-iteration: current
          excluded-statuses: "Done"
