name: Build and Publish Kona FPP Images

on:
  workflow_dispatch:
    inputs:
      asterisc_tag:
        description: Tag for `asterisc` to build the prestate artifacts
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-fpp-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        fpvm: ["asterisc"]
    env:
      IMAGE_NAME: ${{ github.repository }}/kona-fpp-${{ matrix.fpvm }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Authenticate with container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Publish `kona-fpp-${{ matrix.fpvm }}`
        uses: docker/build-push-action@v6
        with:
          file: build/${{ matrix.fpvm }}/${{ matrix.fpvm }}-repro.dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CLIENT_TAG=${{ github.ref_name }}
            ASTERISC_TAG=${{ inputs.asterisc_tag }}
