name: Publish Trusted Sync Binary

on:
  workflow_dispatch:

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository }}/trusted-sync
    steps:
      - uses actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Publish `trusted-sync`
        uses: docker/build-push-action@v6
        with:
          file: examples/trusted-sync/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish-docker-hub:
    name: Publish Trusted Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PERSONAL_DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.PERSONAL_DOCKERHUB_ACCESS_TOKEN_SECRET }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: examples/trusted-sync/Dockerfile
          push: true
          tags: refcell/trusted-sync:latest
